### ISSUE TITLE
variables jQuery

### ISSUE THREAD

**Issue by donnerc** [thirteenfoil8/TM-Code-Doc#10]
Par convention, les objets jQuery sont précédés d'un `$`. Ainsi, au lieu d'écrire

``` javascript
var truc = $('.ma-classe');
```

on utilise plutôt 

``` javascript
var $truc = $('.ma-classe');
```

Ceci permet de rendre le code bien plus lisible en permettant de savoir directement si une variable contient un objet jQuery ou simplement un élément du DOM.

**Comment by thirteenfoil8** [comment]
Conversion effectuée
