### ISSUE TITLE
Utilité de l'onglet *Accueil*

### ISSUE THREAD

**Issue by donnerc** [thirteenfoil8/TM-Code-Doc#11]
L'onglet _Accueil_ est-il vraiment utile? J'ai l'impression que les gens savent ce qu'ils viennent faire sur l'application _exercices_ ...

**Comment by thirteenfoil8** [comment]
Cet onglet là permet à un utilisateur pas encore enregistrer de quand même pouvoir accéder au site sans enregistrement (bien évidemment, il ne peut rien faire avant de s'être enregisté)
