### ISSUE TITLE
Gestion des indices (hints)

### ISSUE THREAD

**Issue by donnerc** [thirteenfoil8/TM-Code-Doc#12]
Il faudra encore mettre en place la gestion des indices qui est pour le moment totalement absente

**Comment by thirteenfoil8** [comment]
Je sais mais j'ai avancé deja un maximum la partie création pour la version
intermédiaire. En ce qui concerne le dépôt git, il y a pas mal de choses
qui restent flous par rapport à ce qu'on doit mettre dedans,... Je ne
savais pas vraiment les exigences pour celui-ci alors j'ai mis dessus tout
le projet

2015-02-02 21:05 GMT+01:00 Cédric Donner notifications@github.com:

> Il faudra encore mettre en place la gestion des indices qui est pour le
> moment totalement absente
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thirteenfoil8/TM-Code-Doc/issues/12.

## 

Florian Genilloud
Etudiant au Collège du Sud
florian.genilloud@gmail.com

**Comment by donnerc** [comment]
Pour le dépôt, il faut tout mettre dedans à part ce qui est inutile ou
gênant. Les fichiers qui changent de manière intempestive mais qui n'ont
rien à voir avec le code source du projet (Exemple les fichiers compilés
`*.pyc` ou tous les fichiers du dossier `.c9` ne devraient pas faire partie
du repo.

Dans le dépôt Sphinx, le dossier `build/` ne devrait pas faire partie du
dépôt non plus, car il s'agit de fichiers qui changent à chaque fois.

Le 2 février 2015 21:07, thirteenfoil8 notifications@github.com a écrit :

> Je sais mais j'ai avancé deja un maximum la partie création pour la
> version
> intermédiaire. En ce qui concerne le dépôt git, il y a pas mal de choses
> qui restent flous par rapport à ce qu'on doit mettre dedans,... Je ne
> savais pas vraiment les exigences pour celui-ci alors j'ai mis dessus tout
> le projet
> 
> 2015-02-02 21:05 GMT+01:00 Cédric Donner notifications@github.com:
> 
> > Il faudra encore mettre en place la gestion des indices qui est pour le
> > moment totalement absente
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/thirteenfoil8/TM-Code-Doc/issues/12.
> 
> ## 
> 
> Florian Genilloud
> Etudiant au Collège du Sud
> florian.genilloud@gmail.com
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thirteenfoil8/TM-Code-Doc/issues/12#issuecomment-72527714
> .

## 

---

Cédric Donner
Rue de Corbières 46
1630 Bulle

natel : 079 309 61 22

**Comment by thirteenfoil8** [comment]
Je me suis rendu compte que la gestion des indices n'est pas vraiment utile puisque nous avons décidé de travailler sur des équations simple de type factorisation ou développement.
