### ISSUE TITLE
Recherche d'exercices

### ISSUE THREAD

**Issue by donnerc** [thirteenfoil8/TM-Code-Doc#14]
Lorsque la liste d'exercices va grandir, il faudra un moyen efficace pour faire une recherche parmi les exercices disponibles ... on pourrait penser par exemple à faire une requête AJAX au serveur pour renvoyer tous les exercices dont le titre contient un certain mot ...

D'autre part, il me semble que chaque nouveau calcul donne lieu à un nouvel exercice. Il vraudrait mieux distinguer types d'exercices (Exemple : équations du 1er degré) et exercice (une équation précise). On pourrait alors imaginer une interface un peu différente permettant de créer la donnée du type d'exercice en ensuite la possibilité de rajouter plusieurs champs différents pour plusieurs exercices différents de ce type.

**Comment by thirteenfoil8** [comment]
La méthode Ajax a été ajouté mais j'ai trouvé plus facile d'utilisation de faire à chaque fois un nouvel exercice avec une nouvelle page car cela permet au prof d'être plus précis sur l' id de chaque exercice et permet également un contrôle d'url plus facile
