### ISSUE TITLE
Doc développeur : mentionner sources des fichiers pompés ailleurs

### ISSUE THREAD

**Issue by donnerc** [thirteenfoil8/TM-Code-Doc#18]
Il faut absolument mentionner les sources des différents codes pris ailleurs (exemple : shop-item.css) https://github.com/thirteenfoil8/TM-Code-Doc/blob/master/webmath/exercises/static/exercises/css/shop-item.css

De manière générale, il faudrait une liste de tous les fichiers pompés ailleurs pour la documentation développeur avec une indication de leur utilité.

**Comment by thirteenfoil8** [comment]
La source a été mentionné.
