### ISSUE TITLE
Supprimer les fichiers inutiles

### ISSUE THREAD

**Issue by donnerc** [thirteenfoil8/TM-Code-Doc#20]
Il faut supprimer les fichiers inutiles du dépôt. Le dossier build à la racine du dossier sphinx devrait notamment être exclu : les fichiers HTML générés n'ont pas leur place dans la documentation. De plus, les dossiers `__pycache__` devraient également être ignorés par git. Pour ce faire, il suffit d'ajouter les lignes suivantes dans le fichier `.gitignore` :+1: 

```
__pycache__
build
```

Il faut ensuite supprimer les dossiers du dépôt avec `git rm -r --cached <nom_dossier>` et faire un commit.

Cela évitera que ces fichiers qui changent tout le temps polluent les commits.

**Comment by thirteenfoil8** [comment]
Les fichiers inutiles ont été supprimé,
