### ISSUE TITLE
Commits de Keran

### ISSUE THREAD

**Issue by donnerc** [thirteenfoil8/TM-Code-Doc#5]
Comment ce fait-il que ton dépôt comporte de nombreux commits de Keran?

**Comment by thirteenfoil8** [comment]
Car j'ai pris le projet webmath qu'on avait en commun et j'ai supprimer les
dossiers des autres et puisque keran avait fait des commits au départ , ils
sont affiché

**Comment by donnerc** [comment]
Je comprends dans ce cas
