### ISSUE TITLE
Intégration LaTeX / MathJAX

### ISSUE THREAD

**Issue by donnerc** [thirteenfoil8/TM-Code-Doc#8]
Est-il prévu de pouvoir faire un rendu mathématique correct de formules / équations entrées sous le format LaTeX / AsciiMath dans le champ _Équation à résoudre_ ? Ce serait un énorme avantage ... Ce n'est probablement pas très compliqué à réaliser.

**Comment by thirteenfoil8** [comment]
Cela a été traité aujourd'hui et est opérationnel sur toutes les pages du site
